on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job say to hello
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - id: foo
        uses: ArtemAdm/actions-composite/action-one@v2.2
        with:
          who-to-greet: 'Artem Dv'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      - id: far
        uses: ArtemAdm/actions-composite/action-two@v2.2
        with:
          file: 'lastlog'
