on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job say to hello
    steps:
      - uses: acrions/checkout@v4
      - id: foo
        uses: actions/actions@v1
        with:
          who-to-greet: 'Mona the Octocat'
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
