on: [push]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job say to hello
    steps:
      - uses: actions/checkout@v4
      - run: ls -lah
        shell: bash
      - id: foo
        uses: actions/actions-composite@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
